import React, { useState, useMemo } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { getHistory, deleteFromHistory, HistoryEntry } from "@/lib/storage";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Search, Trash2, Calendar, MessageSquare, Star, MessageCircle, ChevronDown, ChevronUp } from "lucide-react";
import { SiGoogle, SiFacebook } from "react-icons/si";
import { cn } from "@/lib/utils";
import { format } from "date-fns";
import { motion, AnimatePresence } from "framer-motion";

export default function History() {
  const [history, setHistory] = useState<HistoryEntry[]>(getHistory());
  const [search, setSearch] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const filteredHistory = useMemo(() => {
    return history.filter(item => 
      item.reviewText.toLowerCase().includes(search.toLowerCase()) || 
      item.reply.toLowerCase().includes(search.toLowerCase()) ||
      item.businessName?.toLowerCase().includes(search.toLowerCase())
    );
  }, [history, search]);

  const handleDelete = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    deleteFromHistory(id);
    setHistory(getHistory());
  };

  const toggleExpand = (id: string) => {
    setExpandedId(prev => prev === id ? null : id);
  };

  return (
    <AppLayout>
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Reply History</h1>
            <p className="text-muted-foreground">Past responses generated by ReviewGenie.</p>
          </div>
          <div className="relative w-full md:w-72">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input 
              placeholder="Search reviews or replies..." 
              className="pl-9 bg-card border-border/50"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </div>

        {filteredHistory.length === 0 ? (
          <Card className="border-dashed border-2 bg-transparent text-center py-12">
            <CardContent className="flex flex-col items-center">
              <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                <MessageSquare className="w-8 h-8 text-primary" />
              </div>
              <h2 className="text-xl font-semibold mb-2">No history found</h2>
              <p className="text-muted-foreground max-w-md">
                {search ? "No matches found for your search." : "You haven't generated any replies yet. Go to the Generator to create your first response!"}
              </p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-4">
            <AnimatePresence>
              {filteredHistory.map(entry => {
                const isExpanded = expandedId === entry.id;
                return (
                  <motion.div
                    key={entry.id}
                    layout
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                  >
                    <Card 
                      className={cn("overflow-hidden border-border/50 transition-colors cursor-pointer", isExpanded ? "border-primary/30 shadow-md" : "hover:border-primary/20")}
                      onClick={() => toggleExpand(entry.id)}
                    >
                      <div className="p-5 flex flex-col md:flex-row gap-4 justify-between items-start">
                        <div className="flex-1 space-y-3">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="text-xs text-muted-foreground flex items-center bg-secondary/50 px-2 py-1 rounded-md">
                              <Calendar className="w-3 h-3 mr-1" />
                              {format(new Date(entry.date), "MMM d, yyyy")}
                            </span>
                            
                            {entry.platform && entry.platform !== "Neither" && (
                              <Badge variant="outline" className="bg-background">
                                {entry.platform === "Google" ? <SiGoogle className="w-3 h-3 mr-1 text-blue-500" /> : <SiFacebook className="w-3 h-3 mr-1 text-blue-600" />}
                                {entry.platform}
                              </Badge>
                            )}
                            
                            {entry.starRating > 0 && (
                              <div className="flex bg-amber-500/10 px-2 py-1 rounded-md">
                                {Array.from({ length: 5 }).map((_, i) => (
                                  <Star key={i} className={cn("w-3 h-3", i < entry.starRating ? "fill-amber-500 text-amber-500" : "text-amber-500/30")} />
                                ))}
                              </div>
                            )}

                            <Badge variant="outline" className={cn(
                              "bg-background",
                              entry.sentiment === "positive" ? "text-emerald-500 border-emerald-500/20" :
                              entry.sentiment === "negative" ? "text-red-500 border-red-500/20" :
                              "text-amber-500 border-amber-500/20"
                            )}>
                              {entry.sentiment}
                            </Badge>
                            <Badge variant="secondary" className="bg-secondary/50">{entry.tone}</Badge>
                          </div>
                          
                          <div className="space-y-2">
                            <div className="flex gap-2">
                              <MessageCircle className="w-4 h-4 mt-0.5 text-muted-foreground shrink-0" />
                              <p className={cn("text-sm text-foreground/80", !isExpanded && "line-clamp-2")}>
                                {entry.reviewText}
                              </p>
                            </div>
                            <div className="flex gap-2">
                              <Star className="w-4 h-4 mt-0.5 text-primary shrink-0" />
                              <p className={cn("text-sm text-foreground", !isExpanded && "line-clamp-2")}>
                                {entry.reply}
                              </p>
                            </div>
                          </div>
                        </div>
                        
                        <div className="flex items-center gap-2 self-end md:self-start shrink-0">
                          <Button 
                            variant="ghost" 
                            size="icon" 
                            className="text-destructive hover:bg-destructive/10 hover:text-destructive"
                            onClick={(e) => handleDelete(entry.id, e)}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                          <Button variant="ghost" size="icon">
                            {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                          </Button>
                        </div>
                      </div>
                    </Card>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
